repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-yaml
  - id: pretty-format-json
    args: ['--autofix']
    exclude: 'Pipfile.lock'
  - id: requirements-txt-fixer
    args: [requirements.txt]
  - id: end-of-file-fixer
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
  - id: no-commit-to-branch
    args: ['--branch', 'master']

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4
  hooks:
  - id: flake8

- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black

- repo: https://github.com/pycqa/isort
  rev: 5.6.4
  hooks:
  - id: isort
    args: ['-m3', '--tc']
